"""
Repository for handling research findings.
"""

import logging
from typing import Dict, List

from ...utilties.search_utilities import format_findings_to_text

logger = logging.getLogger(__name__)


class FindingsRepository:
    """Repository for handling research findings."""

    def save_findings(
        self,
        findings: List[Dict],
        current_knowledge: str,
        questions_by_iteration: dict,
        query: str,
    ) -> str:
        """
        Save research findings and return formatted output.

        Args:
            findings: List of research findings
            current_knowledge: Current accumulated knowledge
            questions_by_iteration: Questions generated by iteration
            query: The original research query

        Returns:
            str: Formatted findings
        """
        try:
            return format_findings_to_text(
                findings, current_knowledge, questions_by_iteration
            )
        except Exception as e:
            logger.error(f"Error saving findings: {str(e)}")
            return "Error: Could not format findings due to an error."
