"""
Findings repository for managing research findings.
"""

import logging
from typing import Dict, List

from langchain_core.documents import Document

from ...utilties.search_utilities import (
    format_findings,
    remove_think_tags,
)
from .base_findings import BaseFindingsRepository

logger = logging.getLogger(__name__)


def format_links(links: List[Dict]) -> str:
    """Format a list of links into a readable string.

    Args:
        links: List of dictionaries containing 'title' and 'url' keys

    Returns:
        str: Formatted string of links
    """
    return "\n".join(
        f"{i + 1}. {link['title']}\n   URL: {link['url']}"
        for i, link in enumerate(links)
    )


class FindingsRepository(BaseFindingsRepository):
    """Repository for managing research findings."""

    def __init__(self, model):
        """Initialize the repository.

        Args:
            model: The LLM model to use for synthesis
        """
        super().__init__(model)
        self.findings: Dict[str, List[Dict]] = {}
        self.documents: List[Document] = []
        self.questions_by_iteration: Dict[int, List[str]] = {}

    def add_finding(self, query: str, finding: Dict) -> None:
        """Add a finding for a query."""
        if query not in self.findings:
            self.findings[query] = []
        self.findings[query].append(finding)
        logger.info(
            f"Added finding for query: {query}. Total findings: {len(self.findings[query])}"
        )

        # Store raw synthesized content if it's the final synthesis
        # Check if the phase indicates final synthesis (adjust key if needed)
        if finding.get("phase") == "Final synthesis":
            self.add_finding(query + "_synthesis", finding.get("content", ""))

    def get_findings(self, query: str) -> List[Dict]:
        """Get findings for a query.

        Args:
            query: The query to get findings for

        Returns:
            List of findings for the query
        """
        return self.findings.get(query, [])

    def clear_findings(self, query: str) -> None:
        """Clear findings for a query.

        Args:
            query: The query to clear findings for
        """
        if query in self.findings:
            del self.findings[query]
            logger.info(f"Cleared findings for query: {query}")

    def add_documents(self, documents: List[Document]) -> None:
        """Add documents to the repository.

        Args:
            documents: List of documents to add
        """
        self.documents.extend(documents)
        logger.info(f"Added {len(documents)} documents to repository")

    def set_questions_by_iteration(
        self, questions_by_iteration: Dict[int, List[str]]
    ) -> None:
        """Set the questions by iteration.

        Args:
            questions_by_iteration: Dictionary mapping iteration numbers to lists of questions
        """
        self.questions_by_iteration = questions_by_iteration
        logger.info(f"Set questions for {len(questions_by_iteration)} iterations")

    def format_findings_to_text(
        self, findings_list: List[Dict], synthesized_content: str
    ) -> str:
        """Format findings into a detailed text output using the utility function.

        Args:
            findings_list: List of finding dictionaries from the strategy execution.
            synthesized_content: The final synthesized content generated by the LLM.

        Returns:
            str: Formatted text output.
        """
        logger.info(
            f"Formatting final report. Number of detailed findings: {len(findings_list)}. Synthesized content length: {len(synthesized_content)}. Number of question iterations: {len(self.questions_by_iteration)}"
        )
        # Log details about the inputs
        logger.debug(
            f"Detailed findings list structure (first item type if exists): {type(findings_list[0]) if findings_list else 'Empty'}"
        )
        logger.debug(
            f"Questions by iteration keys: {list(self.questions_by_iteration.keys())}"
        )
        if findings_list:
            logger.debug(f"First finding item keys: {list(findings_list[0].keys())}")

        try:
            # Pass the detailed findings list, the synthesized content (as current_knowledge), and the stored questions
            formatted_report = format_findings(
                findings_list,
                synthesized_content,  # This goes to the 'current_knowledge' param in format_findings
                self.questions_by_iteration,
            )
            logger.info("Successfully formatted final report.")
            return formatted_report
        except Exception as e:
            logger.error(
                f"Error occurred during final report formatting: {str(e)}",
                exc_info=True,
            )
            # Fallback: return just the synthesized content if formatting fails
            return f"Error during final formatting. Raw Synthesized Content:\n\n{synthesized_content}"

    def synthesize_findings(
        self, query: str, sub_queries: List[str], findings: List[str]
    ) -> str:
        """
        Synthesize accumulated knowledge into a final answer.

        Args:
            query: The original query
            sub_queries: List of sub-queries (for context, might be removed later if not needed)
            findings: List of findings strings from previous steps.

        Returns:
            str: Synthesized final answer content.
        """
        try:
            # Convert findings list to accumulated knowledge string
            current_knowledge = "\n\n".join(findings) if findings else ""

            prompt = f"""Synthesize the following accumulated knowledge into a comprehensive answer for the original query.
Format the response with clear sections, citations, and a one-sentence summary, following the structure provided below.

Original Query: {query}

Accumulated Knowledge:
{current_knowledge}

Sub-questions asked (for context):
{chr(10).join(f"- {sq}" for sq in sub_queries)}

Generate a well-structured answer that:
1. Starts with a clear explanation section
2. Organizes information into logical sections with headers
3. Includes citations using [1], [2], etc. for all claims (referencing sources implicitly within the knowledge)
4. Maintains logical flow and coherence
5. Highlights key insights and conclusions
6. Addresses any contradictions or uncertainties found in the knowledge
7. Ends with a one-sentence summary

Format your response strictly as:
**Explanation:**
[Your explanation with citations]

**Section 1:**
[Content with citations]

**Section 2:**
[Content with citations]

...

**Conclusion:**
[Your conclusion with citations]

**One-sentence answer:**
[Your one-sentence summary with citations]
"""

            logger.info(
                f"Synthesizing final answer. Query: '{query}'. Knowledge length: {len(current_knowledge)}. Prompt length: {len(prompt)}"
            )
            # Log first 500 chars of prompt for debugging context length issues
            logger.debug(f"Synthesis prompt (first 500 chars): {prompt[:500]}...")

            try:
                response = self.model.invoke(prompt)
                synthesized_content = remove_think_tags(response.content)
                logger.info(
                    f"Successfully synthesized final answer for query: '{query}'"
                )
                # Return only the synthesized content from the LLM
                return synthesized_content
            except Exception as invoke_error:
                logger.error(
                    f"LLM invocation failed during synthesis for query '{query}': {invoke_error}",
                    exc_info=True,
                )
                # Re-raise or return specific error
                return "Error: Failed to synthesize final answer due to LLM error."

        except Exception as e:
            # Catch potential errors during prompt construction or logging itself
            logger.error(
                f"Error preparing or executing synthesis for query '{query}': {str(e)}",
                exc_info=True,
            )
            # Return a specific error message for synthesis failure
            return "Error: Failed to synthesize final answer from knowledge."
