services:
  local-deep-research:
    {%- if cookiecutter.build %}
    build:
      context: .
      dockerfile: Dockerfile
      target: ldr
    {% else %}
    image: localdeepresearch/local-deep-research
    {% endif %}
    {%- if cookiecutter.host_network %}
    network_mode: host  # Best option for connecting to locally running Ollama
    {% else %}
    networks:
      - ldr-network
    {% endif %}
    ports:
      - "{{cookiecutter.host_port}}:{{cookiecutter.host_port}}"
    environment:
      # Web Interface Settings
      - LDR_WEB_PORT={{cookiecutter.host_port}}
      - LDR_WEB_HOST={{cookiecutter.host_ip}}
      {%- if cookiecutter.enable_ollama %}
      - LDR_LLM_PROVIDER=ollama
      - LDR_LLM_OLLAMA_URL=http://ollama:11434
      {% endif %}
      {%- if cookiecutter.enable_searxng %}
      - LDR_SEARCH_ENGINE_WEB_SEARXNG_DEFAULT_PARAMS_INSTANCE_URL=http://searxng:8080
      {% endif %}
    volumes:
      - ldr_data:/install/.venv/lib/python3.13/site-packages/data/
      - ./local_collections/personal_notes:/local_collections/personal_notes/
      - ./local_collections/project_docs:/local_collections/project_docs/
      - ./local_collections/research_papers:/local_collections/research_papers/
    restart: unless-stopped
    {%- if cookiecutter.enable_ollama or cookiecutter.enable_searxng %}
    depends_on:
      {%- if cookiecutter.enable_ollama %}
      - ollama
      {% endif %}
      {%- if cookiecutter.enable_searxng %}
      - searxng
      {% endif %}
    {% endif %}

  {%- if cookiecutter.enable_ollama %}
  ollama:
    {%- if cookiecutter.enable_gpu and cookiecutter._amd_gpu %}
    image: ollama/ollama:rocm
    {% else %}
    image: ollama/ollama:latest
    {% endif %}
    volumes:
      - ollama_data:/root/.ollama
    {%- if not cookiecutter.host_network %}
    networks:
      - ldr-network
    {% endif %}
    {%- if cookiecutter.enable_gpu %}
    {%- if cookiecutter._nvidia_gpu %}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    {% elif cookiecutter._amd_gpu %}
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    {% endif %}
    {% endif %}
    restart: unless-stopped
  {% endif %}

  {%- if cookiecutter.enable_searxng %}
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    {%- if not cookiecutter.host_network %}
    networks:
      - ldr-network
    {% endif %}
    volumes:
      - searxng_data:/etc/searxng
    restart: unless-stopped
  {% endif %}

volumes:
  ldr_data:
  ollama_data:
  searxng_data:

{%- if not cookiecutter.host_network %}
networks:
  ldr-network:
{% endif %}
